%YAML:1.0

#---------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#---------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 728.7329
Camera1.fy: 729.0125
Camera1.cx: 626.0223
Camera1.cy: 531.8843

Camera1.k1: -0.0463
Camera1.k2: 0.1427
Camera1.p1: 0.00067775
Camera1.p2: -0.00082188
Camera1.k3: -0.089

Camera2.fx: 731.4918
Camera2.fy: 731.7279
Camera2.cx: 614.8181
Camera2.cy: 514.6389

Camera2.k1: -0.0491
Camera2.k2: 0.1516
Camera2.p1: 0.00027016
Camera2.p2: -0.00015604
Camera2.k3: -0.0955

# Camera frames per second 
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Camera resolution
Camera.width: 1224
Camera.height: 1024

# Close/Far threshold
Stereo.ThDepth: 40.0

# Transformation matrix from right camera to left camera
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 0.9992, 0.0060, -0.0400, 0.19632811,
         -0.0070, 0.9996, -0.0257, 0.0029978,
          0.0398, 0.0260,  0.9989, 0.00317689,
          0.0,    0.0,     0.0,    1.0]

#---------------------------------------------------------------------------------------
# ORB Parameters
#---------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum
# response. Firstly we impose iniThFAST. If no corners are detected we impose a lower
# value minThFAST. You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#---------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 1.0
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.15
Viewer.CameraLineWidth: 2.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -10.0
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000.0
