%YAML:1.0

#---------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#---------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 730.271578753826
Camera1.fy: 729.707285068689
Camera1.cx: 610.90462936767
Camera1.cy: 537.715474717007

Camera1.k1: -0.0559502131995934
Camera1.k2: 0.123761456061624
Camera1.p1: 0.00114530935813615
Camera1.p2: -0.00367111451580028
Camera1.k3: -0.0636070725936968

Camera2.fx: 730.575680796265
Camera2.fy: 732.161010099802
Camera2.cx: 610.639915464416
Camera2.cy: 518.5499780933339

Camera2.k1: -0.0616070236014428
Camera2.k2: 0.155957200596806
Camera2.p1: 0.0017265842980712
Camera2.p2: 0.00131774201584002
Camera2.k3: -0.09181347430349431

# Camera frames per second 
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Camera resolution
Camera.width: 1224
Camera.height: 1024

# Close/Far threshold
Stereo.ThDepth: 40.0

# Transformation matrix from right camera to left camera
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 0.99960794, 0.00661203, -0.02720752,  0.19765644
         -0.00728019, 0.99967251, -0.02453295, -0.00266415,
          0.02703640, 0.02472141,  0.99932872,  0.00277772,
          0.00000000, 0.00000000,  0.00000000,  1.00000000]

#---------------------------------------------------------------------------------------
# ORB Parameters
#---------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum
# response. Firstly we impose iniThFAST. If no corners are detected we impose a lower
# value minThFAST. You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#---------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2.0
Viewer.GraphLineWidth: 1.0
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -100.0
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000.0
