%YAML:1.0

#---------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#---------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 728.7329
Camera1.fy: 729.0125
Camera1.cx: 626.0223
Camera1.cy: 531.8843

Camera1.k1: -0.0559502131995934
Camera1.k2: 0.123761456061624
Camera1.p1: 0.00114530935813615
Camera1.p2: -0.00367111451580028
Camera1.k3: -0.0636070725936968

# Camera frames per second 
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Camera resolution
Camera.width: 1224
Camera.height: 1024

#---------------------------------------------------------------------------------------
# ORB Parameters
#---------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum
# response. Firstly we impose iniThFAST. If no corners are detected we impose a lower
# value minThFAST. You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#---------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 1.0
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.15
Viewer.CameraLineWidth: 2.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -10.0
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000.0
